### ISSUE TITLE
Font caching issues

### ISSUE THREAD

**Issue by bbrdaric** [fontello/fontello#127]
Hi,

I noticed that WebKit browsers (especially Chrome) are brutally caching resources. When I update my Fontello font file, I regularly need to hit CTRL+F5 for Chrome to clear cache and take that new font file. 

So it seems every user needs to do this to have new icons.

Can you consider adding one checkbox next to filename input on Fontello front page so that option would add generation timestamp for resources in @font-face that is in fontello.css and in that way force the browser to pick up new file?

``` CSS
@font-face {
  font-family: 'fontello';
  src: url("../font/fontello.eot?1360161745");
/*  src: url("../font/fontello.eot?1360161745#iefix") format('embedded-opentype'), url("../font/fontello.woff?1360161745") format('woff'), url("../font/fontello.ttf") format('truetype'), 

...
```

**Comment by antusus** [comment]
Hello,

we are using fontello in our project and we are having some issues with this solution to prevent font caching. We are using HTML5 application cache because we want to manage what should be refreshed when. In order to make fontello fonts work with this we have to either remove the generated timestamp or add it to cache manifest. Could it be possible to add a flag and specify during font generation if I want to add this timestamp or not?
