### ISSUE TITLE
Using less is possible from this tool?

### ISSUE THREAD

**Issue by sergiohermes** [fontello/fontello#178]
It is possible to generate a less? There are systems that work with the cache data generated from less.

So when you need to modify or add a new icon only update ...

Could be clearer?

hug,

**Comment by imolorhe** [comment]
Hi @puzrin, when working on a large project with subprojects that use their own subsets of the selected set of icons being used in the entire project. Like in the development of various sub projects under the same organization. The organization could have a large set of icons containing icons used by various subprojects. However, because of the large size of the entire icon set where some of the icons would not be used by a subproject, it is recommended that the subproject downloads only a subset of the icons to be used. In this same setup, the CSS files are compiled from SCSS files such that only one CSS file is served. Given this scenario, the current font generation setup of fontello makes achieving this very tedious. Currently, the way we use it is that all the subprojects download the entire icon font containing both icons in use and those not in use. Whenever any of the subprojects need a new icon, the icon is added to the icon set on fontello using the previously generated config.json file. The new icon fonts and styles are then downloaded, unzipped, and manually converted to SCSS files that can be imported into the project.

Frankly if this process can be simplified in anyway, probably with a grunt task that automatically generates SCSS files and icon fonts from fontello  based on the specified config.json file and an exclude/include list of icons, it would be really helpful. That way, every project can have their own individual config file or list of icons.

**Comment by puzrin** [comment]
@imolorhe each archive contains `config.json` file, you can combine your CSS as you wish with external script. It's impossible to include all custom features to fontello. It's designed to be extendable.
