### ISSUE TITLE
SVG import bug reports

### ISSUE THREAD

**Issue by puzrin** [fontello/fontello#206]
If you have problems with importing SVG images, please check first, that all image contours are joined into single outline (dont's confuse "joining" with "grouping"). If not - do it in your editor.

Then, if no success, or bad result - attach source file to this ticket or gist.

I'll try to automate importing as much as possible. Just need feedback to understand standard cases.

**Comment by exocom** [comment]
@puzrin great job on fontello! My team is trying to automate our icon process. So far we are able to create a config.json, however, when we drop it on fontello.com the paths do not get processed by your "importer" process, and all of the icons are smaller than normal.

If we pull out the path and put it into an .svg and drop that on fontello.com it works! I believe this is because the path was process by the "importer" mentioned above.

1. Is there anyway I can invoke the "importer" on all of the paths when I drop a config.json file? This way we don't have to drop 1 file at a time.

2. I've cloned down fontello/fontello but I can't see to locate where the "importer" function is, can you point me in the right direction? I would be happy to add the feature once I know where to look.

**Comment by puzrin** [comment]
> 1 file at a time

You can drop multiple files

> can't see to locate where the "importer" function is

Start looking from this file https://github.com/fontello/fontello/blob/master/client/app/import/import.js

Note about this bug with custom icons https://github.com/fontello/fontello/blob/master/client/app/import/import.js

**Comment by tk19** [comment]
heres my file https://drive.google.com/file/d/0B0MwIfxbadOPVHYzMExMQXg2ajA/view?usp=sharing
Shows the same error! 'Convert to compound image manually!' I have tried all I Know!! Its still not working!! The svg is fine when I open in browser but parts of it are missing when I upload.

**Comment by tatidesigner** [comment]
Yes! I´m a designer but I make miracles... so I have got the same shit... How can I make a circle, skipping the tag circle into svg file?
