### ISSUE TITLE
Feature request: sorting

### ISSUE THREAD

**Issue by livelysalt** [fontello/fontello#240]
It would be handy to be able to sort the custom font set, either by code value, or ideally by dragging to rearrange the order.

**Comment by puzrin** [comment]
Our best scientists and engineers tried hard to solve this problem for 2 years, and they almost succeeded. Be in touch, i'll add more info soon.

**Comment by puzrin** [comment]
Fixed by:

- https://github.com/fontello/fontello/commit/54915d1b18d47ca655d456456a4fb485e805edf3
- https://github.com/fontello/fontello/commit/20a5481df3ae4cd6ae2cbdc5941128de853c1345
- https://github.com/fontello/fontello/commit/4d04fb4d4471a7e20bfaaccc8f011b0ac5c09d25
- https://github.com/fontello/fontello/commit/379e14e84102c473cf9d5d8b9b5daa25dfedd10c

Will try to deploy tomorrow.
