### ISSUE TITLE
Update FontAwesome to 4.3.0

### ISSUE THREAD

**Issue by puzrin** [fontello/fontello#384]
http://fontawesome.io/whats-new/

4.3.0 released

**Comment by cheeaun** [comment]
:+1:

**Comment by collinsethans** [comment]
Will be great to have this 4.3.0 update soon.

**Comment by BreadMaker** [comment]
In the meantime, you should consider insert the icons you need from the Font-Awesome-SVG-PNG project. https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg

**Comment by francoismassart** [comment]
**How does fontello plan to manage having several versions of the same font set?**

At this time, fontawesome is available within fontello at version 4.1.0 but what will happen when 4.3.0 is added to fontello?

Will we have both versions living side by side?
Or will the latest version (4.3.0) overwrite the previous version (4.1.0)?

I'm willing to help but I need to know how to handle it.

I guess that only the latest version will remain but some points are just not clear.

For example in 4.1.0 the class `.fa-times` does not exist but the icon do exist as `.fa-close`.
How do we handle this? I guess we want to keep it backward compatible but then we're stuck with the old name...

Is there some guidelines about updating an existing font set?

**Comment by francoismassart** [comment]
@puzrin is there a guide on how to upgrade a webfont ?
I'd like to help!

**Comment by francoismassart** [comment]
I'm working on updating FA to 4.3.0.
I had to import it all, because I cannot edit the existing 4.1.0 and I took the opportunity to use names that are as close as possible to the native FA classes... 
I should have a zip ready for review today.

**Comment by francoismassart** [comment]
@puzrin Could you add the FontAwesome 4.3.0 I took the time to build ?

Via the fontello generated webfont zip file below:
https://github.com/francoismassart/fa-to-fontello/raw/master/fontello-9d75eb43.zip

Or via the config.json
https://github.com/francoismassart/fa-to-fontello/raw/master/config.json

Let me know if you have any questions or if I can help.

Here is what I did:

1. Manually download FA 4.3.0
2. Unzip it
3. Drag the SVG font on the webpage of fontello.com
4. Left intentionally the first "empty" icon as is in order to keep the same unicode used by FA (as defined in FA scss source code)
5. I did write and run a script inside the console of my browser to copy over the properties of each icon
6. The name is as it is defined by FA 4.3.0 itself (user can always rename icons but I want to stay as close as possible to native FA, that will be easier to upgrade the next time too if we keep the same names)
7. Keywords were copied from 4.1.0 icons (using a script + manually when required)
8. Selected every icon of my custom font (which is FA 4.3.0)
9. Download and share it with explaination here and now ;-)

About the aliases, I decided with my team to avoid using them.
Instead we use the classname that aliases point to... The original icon itself.

Can you let me know if it is OK for you to add on fontello.com?
Thank you

**Comment by francoismassart** [comment]
Any news on this?

**Comment by Grawl** [comment]
I really appreciate this because of different naming in current FontAwesome icons and Fontello ones. There are a lot of difference, such as olf `circle-notch` instead of new `circle-o-notch` or `ok` instead of `check`.

My idea is to build customized font for my application with similar with FontAwesome icon names and my custom ones from other icon packs and our unique. All into one font. And I have to fix all `-alt` to `-o` and so on.

So come on, just update it. We are will be happy.

**Comment by francoismassart** [comment]
@Grawl if you want, you can already do this.
Just drag and drop the config.json file
https://github.com/francoismassart/fa-to-fontello/raw/master/config.json
into fontello UI then you can start a custom font which already contains the entire FA 3.4.3 icons and their correct names and tags.

Then you can complete it by dragging SVG source font file on top of that...

**Comment by Grawl** [comment]
Oh cool. Will do it tomorrow.
Will it replace current old FA version on Fontello?

**Comment by francoismassart** [comment]
No, it'll not replace the existing FA, it'll just create a custom font that happen to have all the icons of FA and their correct names...

When you're done just make sure you back up the `config.json` file included in your downloaded zip.

**Comment by Grawl** [comment]
No, I'm not about my custom icon set, I'm about your plans to update FA in Fontello :)

**Comment by francoismassart** [comment]
Not up to me... But on our side we already use it as a custom icon set.
I did my part.

**Comment by dandv** [comment]
:+1: for the latest Font-Awesome and clarifying how multiple fonts are stored side-by-side.

**Comment by quelo83** [comment]
+1

**Comment by puzrin** [comment]
done

**Comment by Grawl** [comment]
awesome!

**Comment by dandv** [comment]
@puzrin: how does Fontello manage multiple versions of the same font?

See @francoismassart's [question](https://github.com/fontello/fontello/issues/384#issuecomment-98712404).

**Comment by puzrin** [comment]
@dandv It keeps only latest version, but every glyth has intact unique id, used on import. So, if glyph was not removed from  collectiom, old configs will fork with next version.
