### ISSUE TITLE
Strange behaviour of fontello fonts on iOS

### ISSUE THREAD

**Issue by bsaglio** [fontello/fontello#441]
I've just found out a little CSS trick to avoid a 10px shift on iOS with my fontello fonts.

http://wgs3.s3.amazonaws.com/perso/bsaglio/bug-jardiland/test.html

This page shows an example of a 3 tabs menu using either a webfont created with fontello based on SVG files or standard arial font.

Everything ok on my Desktop and on Androïd devices. But with my iPhone 5 (either with Safari or Chrome 44.0.2403.65), I'm getting a 10px shift on my fontello font after clicking once to select another tab... except if I use a CSS line-height property !

Note that this problem does not appear when I use the iPhone device mode in my webdevelopper tools on my desktop.

Does anyone know if it's a bug or not ?

**Comment by nicooprat** [comment]
I guess it's not really a bug... browsers (and OSes) font rendering differ a lot from one to another. It's one of the argument of using SVG as icons instead of custom fonts : https://css-tricks.com/icon-fonts-vs-svg/

I personally often set the line-height to ensure there're no problem, but it's never pixel-perfect in every case.

**Comment by puzrin** [comment]
Is it still a problem? I've updated font builder couple of weeks ago.

**Comment by puzrin** [comment]
Close - timed out
