### ISSUE TITLE
Upload to Fontello doesn't display all paths (vectorized) 

### ISSUE THREAD

**Issue by Naemy** [fontello/fontello#442]
On Mac OS X, when I upload the SVG file on the Fontello website (Chrome, drag'n'drop) not every path displays (yet they are been properly vectorized) .
I've tried 'grouping' paths, exporting it to SVG Tiny 1.1 or SVG 1.1 yet nothing seems to work so far.

Here's the SVG file we used: https://www.dropbox.com/s/0ev0gywef8wlqki/add.svg?dl=0
The export that I get: https://www.dropbox.com/s/53zk6wfsimiikjg/fontello-92ca3910.zip?dl=0

Thanks in advance!

**Comment by booti386** [comment]
It's not a bug (or at least not unexpected). While importing your SVG file, the website shows a warning, stating that polygon tags are not supported. The cross is drawn using :
```xml
    <polygon class="st0" points="15.5,1 14,1 14,3 12,3 12,4.5 14,4.5 14,6.5 15.5,6.5 15.5,4.5 17.5,4.5 17.5,4.4 17.5,3.5 17.5,3    15.5,3  "/>
```
If you open your image into a text editor and remove this line, you will get exactly the same result (the cross is missing).
You can follow the tips here (followed successfully with your svg) to get a Fontello compatible image: https://github.com/fontello/fontello/wiki/How-to-use-custom-images#preparing-images-in-inkscape

**Comment by Naemy** [comment]
Just checked it out. When I follow the illustrator steps (compound path -> make), I end up with this file:
https://www.dropbox.com/s/uhrbqgmto8xn3vy/add_illustrator-export.svg?dl=0

When I upload it, it seems empty ( https://www.dropbox.com/s/3sjz4qb6f5kc87x/Capture%20d%27%C3%A9cran%202015-09-15%2018.32.58.png?dl=0 ) yet on preview it is appearing on some weird emplacement ( https://www.dropbox.com/s/jjwtig8mkf2o6ey/Capture%20d%27%C3%A9cran%202015-09-15%2018.33.14.png?dl=0 ) 

I'll try with Inkscape later. 
Thank you for the helping hand anyway, that was helpful.

**Comment by booti386** [comment]
The problem this time looks like a huge offset added to the image coordinates (-288; 413.2) (visible in a text editor in "viewBox"), that fontello doesn't seem to handle properly (probably a real bug this time). A quick fix could be to find what parameter caused Illustrator to suddenly add this offset (wasn't present in the original svg), and change it back to (0; 0).

In the hope it will be useful :)

**Comment by Naemy** [comment]
ANY export via Illustrator (SVG 1.1) changes the viewBox settings to disproportionate coordinates here. (the original export was made with Sketch)

Are you sure it is the only issue here ? Setting the viewBox back to the original SVG (viewBox="0 0 17.5 15.7" style="enable-background:new 0 0 17.5 15.7;") doesn't seem to change anything about the offset issue in Fontello.

Maybe Sketch and Illustrator handle their exports in differents ways that Fontello can't handle when mixed together ?

It is. thanks. : )

**Comment by booti386** [comment]
Yes, it is the only issue, but trivially change the view box coordinates isn't the only thing to do. If you look closer inside the file, you'll see the following tag:
```xml
<path class="st0" d="M-272,427.2c0,0.1-0.1,0.3-0.3,0.3h-14c-0.1,0-0.3-0.1-0.3-0.3v-8h9.6v-1.6h-9.5V415c0-0.1,0.1-0.3,0.3-0.3h4.1
	c0.1,0,0.3,0.1,0.3,0.2v1.5h4.8V415h-3.4l0,0c0-1-0.8-1.7-1.8-1.7h-4c-1-0.1-1.8,0.7-1.8,1.7v2.7v1.5v8c0,1,0.8,1.8,1.8,1.8h14
	c1,0,1.8-0.8,1.8-1.8v-6.5h-1.6V427.2z M-272.5,414.2h-1.5v2h-2v1.5h2v2h1.5v-2h2v-0.1v-0.9v-0.5h-2V414.2z"/>
```
Its purpose is to define the drawing itself. It contains multiple directives, including "M", that specifies the point where you start to draw a continuous set of linked points. The format is "Mx,y", and as you can see, computed final coords are (M.x - viewBox.x; M.y - viewBox.y). Because fontello seems to completely ignore the viewBox, if you want to fix the image by hand, you must also edit each M directive to (oldM.x - oldviewBox.x, oldM.y - oldviewBox.y). It's pretty easy for this svg (only 2 or 3), but can quickly become very annoying as the image complexity increases. So maybe you should recheck Illustrator export options, or try with Inkscape, I don't really know.
Good luck ! :)

**Comment by puzrin** [comment]
Not related to fontello, but i hope you solved it.

@booti386 thanks for your help!
