### ISSUE TITLE
Outlined Icons

### ISSUE THREAD

**Issue by mischugo** [fontello/fontello#452]
Hi,
first let me say - Fontello is awesome :-)
Next: i have upload an outlined svg but i get back a color filled for download.
Is it a issue or my misunderstanding about anything?

Thanks, Maik

**Comment by yyang** [comment]
Hey,

I think we need to "create outline" for that outlined svg image in illustrator or other software in order to let fontello recognizes.

They simply recognizes shape but not how we fill it or how we outline it.

S

Sent from my iPhone

On Nov 3, 2015, at 4:26 PM, mischugo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
first let me say - Fontello is awesome :-)
Next: i have upload an outlined svg but i get back a color filled for download.
Is it a issue or my misunderstanding about anything?

Thanks, Maik

-

**Comment by mischugo** [comment]
Thanks!
