### ISSUE TITLE
Font Icons for Windows

### ISSUE THREAD

**Issue by pbmasigla** [fontello/fontello#481]
Having an issue with new icon font for Windows browsers (tested on Chrome 49 and Firefox 44).  Icons are now oddly appearing lower than their original spots (old version of the icon font with the same icons had icons in the right place). Last working icon font was made just before the rebuilding icons PR #846117efeabd903e94cab50bae5fbf314905a6e7. 

<img width="135" alt="screen shot 2016-03-08 at 3 03 26 pm" src="https://cloud.githubusercontent.com/assets/1839970/13615074/95545cf6-e541-11e5-84da-f05f02407f62.png">

I'm thinking it has to do with that updated PR? Any ideas or solutions? Works perfectly on Mac browsers.

**Comment by puzrin** [comment]
1. Problem can be caused by new icons like in #477. Try to split you collection and check if reduced sets still buggy.
2. I've just updated svg2ttf, try to generate font again.

Also:

- Tell your win version and (if possible) can this problem be reproduced by one of MS images for virtualbox
- Is this problem reproducible on another computers?
- Attach your config or zip.

**Comment by pbmasigla** [comment]
[st-icon-font.zip](https://github.com/fontello/fontello/files/163958/st-icon-font.zip)

Can be reproduced on other computers, and I'll try splitting the collection now. Thanks for the quick reply.

**Comment by puzrin** [comment]
Any news?

**Comment by puzrin** [comment]
Close - no feedback.
