### ISSUE TITLE
Multiselect – Hold 'Shift' and/or hold 'Cmd'

### ISSUE THREAD

**Issue by eightyfive** [fontello/fontello#501]
_2 enhancements_:

1. It would be great if the multipleselect was working when holding 'Shift' and/or 'Cmd' keys. Exactly like on a computer OS.
2. A checkbox 'Select all' per collection would be great as well.

_2 side notes / bugs-ish_:

1. The drag n' drop multiselect is very slow for me. Dunno if this happens to others, but when I drag n' drop select multiple icons I have to wait a loooong time before the webapp actually selects the actual icons on page. It also prevents me from using the webapp meanwhile (it freezes). I'm using Chrome (latest).
2. Furthermore, when drag n' droppin', it is impossible to scroll down the screen as you select the icons. So you cannot really a whole bunch at a time if bunch of icons is taller than screen estate.

Thanks for fontello anyway, just trying to point enhancements.

Cheers,
Ben

**Comment by puzrin** [comment]
Please split issues to independent ones, to make things trackable & discussable.

- "Select all" needs interface rework and will be done in new design (see appropriate issue with screenshots). But no deadlines.
- Updates when a lot of icons selected are slow :( . That's a known issue. Not considered as critical, because is not normal to select 2K icons on practice (at least, i don't know such use cases).

**Comment by puzrin** [comment]
I've closed this issue as not organized well, but you can create more simple ones anytime you wish.

**Comment by eightyfive** [comment]
Hey, I did split the issues:

https://github.com/fontello/fontello/issues/509
https://github.com/fontello/fontello/issues/508
https://github.com/fontello/fontello/issues/507
https://github.com/fontello/fontello/issues/506

Feel free to close them if not applicable / relevant / duplicate / etc.

**Comment by puzrin** [comment]
Thanks
