### ISSUE TITLE
uploading zip or json file produces duplicate icons

### ISSUE THREAD

**Issue by JohnEcks** [fontello/fontello#523]
I started noticing this about a month ago.

If I upload a zip or json file I get duplicate icons for most of them. I'm using latest Firefox on OS X Mavericks. I'm not sure if this is a problem with the website, because I'm using various custom icons I uploaded with SVG, or if maybe one of the zips was corrupted and since I keep uploading them as I add icons it's perpetuating it.

Their also seems to be a large "period" `.` added at the end with the name "glyph."

This isn't a huge deal because the duplicates are un-selected by default. Just figured I'd bring it up in case anyone else has seen this behavior.

Here's a screenshot.

![fontello_duplicates](https://cloud.githubusercontent.com/assets/20800099/17815292/a6d0d298-6601-11e6-88ab-ef18bd706c69.jpg)

**Comment by leobru** [comment]
This is convenient if the goal is to create synonyms (e. g. if I want the same glyph available under "A" and "a").

**Comment by JohnEcks** [comment]
yes. I'd personally like it better as an option rather than default since it clutters the view.

**Comment by leobru** [comment]
For me uploading config.json doesn't duplicate, likely because the uids of all icons are identical. Uploading the SVG font file does duplicate, as it should (but it seems that the codepoints aren't uniquified until I go to the codepoint reassignment tab).
It could be that uploading a zip file uses the SVG font file in the archive instead of the config.json file (that would be a mistake). 
I'm fine with replication happening only if a font.svg is uploaded.

**Comment by puzrin** [comment]
That's done intentionally, to allow megre custom icons from different sets. Also, custom icons area has link for quick cleanup.

I know, that's not ideal, but looks like acceptable trade-off.
