### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by webocoders** [fontello/fontello#677]

**Comment by AvnerCohen** [comment]
Came across this - https://stackoverflow.com/questions/50522604/fontello-is-down-can-i-use-any-alternative-for-it - but would be good if people can point to additional alternatives.

**Comment by esmaei1** [comment]
it will be back or is down for ever?

**Comment by AvnerCohen** [comment]
My suggestion for an alternative is to use the following docker image:

https://hub.docker.com/r/unico/fontello/

```
docker pull unico/fontello
docker run -it -p  3000:3000 -d unico/fontello
```

**Comment by nreynis** [comment]
`unico/fontello` seems outdated, it corrupts most of my icons.

**Comment by saschalalala** [comment]
@AvnerCohen Ubuntu 14.04, Node 4, Fontello Branch 5.3.0 which doesn't even exist anymore, this isn't a good suggestion.

**Comment by AvnerCohen** [comment]
@saschalalala  @nreynis My usage is extremely minimal and basic, this docker, while old, has worked for me.

**Comment by AvnerCohen** [comment]
Also, looking at the build scripts, they are very old and only relevant to older version - https://github.com/fontello/fontello/blob/master/support/ttfautohint-ubuntu-12.04.sh

So my guess is that the active site is not very different (out side of the diff in the fontello version, which should be very easy to change on the docker file).

**Comment by webocoders** [comment]
Any response from authors?

**Comment by puzrin** [comment]
Restarted, thanks for info. Main process crashed for unknown reasons.

**Comment by djagya** [comment]
@puzrin I'm really sorry, I think it was me who crashed your server.
To everyone: I didn't mean it.

I was implementing a simplistic library that would find icons used in the projects and automatically generate config and fonts using fontello API. Was trying to send a multipart request using just node http module, so it took me multiple attempts and at one point it seems one of the requests was made with a malformed body that crashed the server - I tested it on the local fontello version then.

You probably should look into adding a monitoring daemon if it's not already integrated, something like `pm2`, since your server might potentially crash again at some point.

**Comment by AvnerCohen** [comment]
I guess this case can be closed.

For what it's worth, I've created an updated docker image based on latest version - https://hub.docker.com/r/avnerner/fontello_server/

**Comment by puzrin** [comment]
@djagya do you have an example of such bad request? Fontello should be resistant to requests of any type.

**Comment by djagya** [comment]
@puzrin sorry, I won't be able to reproduce it, but the issue was in an incorrectly formed `multipart/form-data` request body.

**Comment by puzrin** [comment]
Ok, i reported issue to `multiparty`, but probably this could be error in old node streams. Close, since node was updated.
